version: '2'

services:

  mongo:
    image: mongo:3.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes_from:
      - mongodata
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongodata:
      image: mongo:3.4
      command: "true"
